/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppHrIndexRouteImport } from './routes/app/hr/index'
import { Route as AppEmployeeIndexRouteImport } from './routes/app/employee/index'
import { Route as AppEmployeePayslipRouteImport } from './routes/app/employee/payslip'
import { Route as AppEmployeePayrollHistoryRouteImport } from './routes/app/employee/payroll-history'
import { Route as AppEmployeeLeaveRouteImport } from './routes/app/employee/leave'
import { Route as AppEmployeeAttendanceRouteImport } from './routes/app/employee/attendance'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppHrIndexRoute = AppHrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeeIndexRoute = AppEmployeeIndexRouteImport.update({
  id: '/employee/',
  path: '/employee/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeePayslipRoute = AppEmployeePayslipRouteImport.update({
  id: '/employee/payslip',
  path: '/employee/payslip',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeePayrollHistoryRoute =
  AppEmployeePayrollHistoryRouteImport.update({
    id: '/employee/payroll-history',
    path: '/employee/payroll-history',
    getParentRoute: () => AppRoute,
  } as any)
const AppEmployeeLeaveRoute = AppEmployeeLeaveRouteImport.update({
  id: '/employee/leave',
  path: '/employee/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeeAttendanceRoute = AppEmployeeAttendanceRouteImport.update({
  id: '/employee/attendance',
  path: '/employee/attendance',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/employee/attendance': typeof AppEmployeeAttendanceRoute
  '/app/employee/leave': typeof AppEmployeeLeaveRoute
  '/app/employee/payroll-history': typeof AppEmployeePayrollHistoryRoute
  '/app/employee/payslip': typeof AppEmployeePayslipRoute
  '/app/employee/': typeof AppEmployeeIndexRoute
  '/app/hr/': typeof AppHrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/employee/attendance': typeof AppEmployeeAttendanceRoute
  '/app/employee/leave': typeof AppEmployeeLeaveRoute
  '/app/employee/payroll-history': typeof AppEmployeePayrollHistoryRoute
  '/app/employee/payslip': typeof AppEmployeePayslipRoute
  '/app/employee': typeof AppEmployeeIndexRoute
  '/app/hr': typeof AppHrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/employee/attendance': typeof AppEmployeeAttendanceRoute
  '/app/employee/leave': typeof AppEmployeeLeaveRoute
  '/app/employee/payroll-history': typeof AppEmployeePayrollHistoryRoute
  '/app/employee/payslip': typeof AppEmployeePayslipRoute
  '/app/employee/': typeof AppEmployeeIndexRoute
  '/app/hr/': typeof AppHrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/profile'
    | '/app/employee/attendance'
    | '/app/employee/leave'
    | '/app/employee/payroll-history'
    | '/app/employee/payslip'
    | '/app/employee/'
    | '/app/hr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/profile'
    | '/app/employee/attendance'
    | '/app/employee/leave'
    | '/app/employee/payroll-history'
    | '/app/employee/payslip'
    | '/app/employee'
    | '/app/hr'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/profile'
    | '/app/employee/attendance'
    | '/app/employee/leave'
    | '/app/employee/payroll-history'
    | '/app/employee/payslip'
    | '/app/employee/'
    | '/app/hr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hr/': {
      id: '/app/hr/'
      path: '/hr'
      fullPath: '/app/hr/'
      preLoaderRoute: typeof AppHrIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employee/': {
      id: '/app/employee/'
      path: '/employee'
      fullPath: '/app/employee/'
      preLoaderRoute: typeof AppEmployeeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employee/payslip': {
      id: '/app/employee/payslip'
      path: '/employee/payslip'
      fullPath: '/app/employee/payslip'
      preLoaderRoute: typeof AppEmployeePayslipRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employee/payroll-history': {
      id: '/app/employee/payroll-history'
      path: '/employee/payroll-history'
      fullPath: '/app/employee/payroll-history'
      preLoaderRoute: typeof AppEmployeePayrollHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employee/leave': {
      id: '/app/employee/leave'
      path: '/employee/leave'
      fullPath: '/app/employee/leave'
      preLoaderRoute: typeof AppEmployeeLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employee/attendance': {
      id: '/app/employee/attendance'
      path: '/employee/attendance'
      fullPath: '/app/employee/attendance'
      preLoaderRoute: typeof AppEmployeeAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppProfileRoute: typeof AppProfileRoute
  AppEmployeeAttendanceRoute: typeof AppEmployeeAttendanceRoute
  AppEmployeeLeaveRoute: typeof AppEmployeeLeaveRoute
  AppEmployeePayrollHistoryRoute: typeof AppEmployeePayrollHistoryRoute
  AppEmployeePayslipRoute: typeof AppEmployeePayslipRoute
  AppEmployeeIndexRoute: typeof AppEmployeeIndexRoute
  AppHrIndexRoute: typeof AppHrIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppEmployeeAttendanceRoute: AppEmployeeAttendanceRoute,
  AppEmployeeLeaveRoute: AppEmployeeLeaveRoute,
  AppEmployeePayrollHistoryRoute: AppEmployeePayrollHistoryRoute,
  AppEmployeePayslipRoute: AppEmployeePayslipRoute,
  AppEmployeeIndexRoute: AppEmployeeIndexRoute,
  AppHrIndexRoute: AppHrIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
